site_name: Tilt Integration Documentation
site_description: Documentation for third-party developers integrating with Tilt
site_author: Tilt Team

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

repo_name: tilt-energy/integration_documentation
repo_url: https://github.com/tilt-energy/integration_documentation
edit_uri: edit/main/docs/

plugins:
  - redoc-tag:
      background: "#ffffff"
      height: "80vh"

nav:
  - Introduction:
    - Overview: index.md
  - Core Concepts:
    - Terminology: concepts/terminology.md
  - API Specification:
    - Overview: api/overview.md
    - Reference: api/reference.md
    - Validation: api/validation.md
  - Contributing:
    - Contributing: contributing.md

markdown_extensions:
  - admonition  # For callouts, notes, and warnings
  - codehilite  # For syntax highlighting
  - toc:        # For table of contents
      permalink: true
  - pymdownx.superfences  # For better code block handling
  - pymdownx.tasklist     # For checkboxes in task lists
  - attr_list             # For adding attributes to elements
  - md_in_html            # For using HTML in markdown

extra_javascript:
  - https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js
